common.no-data=No Data
common.feat=Feat
common.background=Background
common.species=Species
common.button.save=Save
common.button.search=Search
common.button.reset=Reset
common.button.clear=Clear
common.button.add=Add
common.button.confirm=Confirm
common.button.select=Select
common.button.delete=Delete
common.button.cancel=Cancel
common.button.remove=Remove
common.button.hide=Hide
common.button.show=Show
common.button.yes=Yes
common.button.no=No
common.button.save_to_url=Save to URL
common.button.save_to_file=Save to File
common.button.load_from_file=Load from File
common.button.copy_as_text=Copy as Text
common.tabs.stat_block=Stat Block
common.tabs.info=Info
common.tabs.images=Images
common.tabs.data=Data
common.tabs.markdown=Markdown
common.tabs.no_info=No information available.
common.tabs.no_image=No images available
common.filter.filter_search_for=Filter/Search for
page.book.page_subtitle=Browse content. Press F to find, and G to go to page.
page.enconterbuilder.rules_note=Based on the encounter building rules in the
page.enconterbuilder.back_to_stat_blocks=Back to Stat Blocks
page.enconterbuilder.shift_for_multi_line_format=Shift for Multi-Line Format
page.enconterbuilder.shift_to_reset_players=Shift to Reset Players
page.backgrounds.alert=Alert
page.backgrounds.crafter=Crafter
page.backgrounds.healer=Healer
page.backgrounds.initiate_of_high_sorcery=Initiate of High Sorcery
page.backgrounds.lucky=Lucky
page.backgrounds.musician=Musician
page.backgrounds.rune_shaper=Rune Shaper
page.backgrounds.savage_attacker=Savage Attacker
page.backgrounds.scion_of_the_outer_planes=Scion of the Outer Planes
page.backgrounds.skilled=Skilled
page.backgrounds.squire_of_solamnia=Squire of Solamnia
page.backgrounds.Strike of the Giants=Strike of the Giants
page.backgrounds.Strixhaven Initiate=Strixhaven Initiate
page.backgrounds.Tavern Brawler=Tavern Brawler
page.backgrounds.tough=Tough
page.backgrounds.magic_initiate=Magic Initiate
page.backgrounds.magic_initiate__cleric=Magic Initiate; Cleric
page.backgrounds.magic_initiate__druid=Magic Initiate; Druid
page.backgrounds.magic_initiate__wizard=Magic Initiate; Wizard
page.feats.repeatable=Repeatable
page.feats.not_repeatable=Not Repeatable
page.charcreationoptions.supernatural_gift=Supernatural Gift
page.charcreationoptions.optional_feature=Optional Feature
page.charcreationoptions.dark_gift=Dark Gift
page.charcreationoptions.replacement_feature__background=Replacement Feature: Background
page.charcreationoptions.character_secret=Character Secret
page.optionalfeatures.artificer_infusion=Artificer Infusion
page.optionalfeatures.elemental_discipline=Elemental Discipline
page.optionalfeatures.eldritch_invocation=Eldritch Invocation
page.optionalfeatures.metamagic=Metamagic
page.optionalfeatures.maneuver=Maneuver
page.optionalfeatures.maneuver__battle_master=Maneuver, Battle Master
page.optionalfeatures.maneuver__cavalier=Maneuver, Cavalier
page.optionalfeatures.arcane_shot=Arcane Shot
page.optionalfeatures.other=Other
page.optionalfeatures.fighting_style__fighter=Fighting Style; Fighter
page.optionalfeatures.fighting_style__bard=Fighting Style; Bard
page.optionalfeatures.fighting_style__paladin=Fighting Style; Paladin
page.optionalfeatures.fighting_style__ranger=Fighting Style; Ranger
page.optionalfeatures.pact_boon=Pact Boon
page.optionalfeatures.rune_knight_rune=Rune Knight Rune
page.optionalfeatures.alchemical_formula=Alchemical Formula
page.optionalfeatures.travelers_trick=Traveler's Trick
page.statgen.additional_feats=Additional Feats
page.statgen.number_of_additional_feats=Number of additional feats
page.lootgen.magic_item_table_=Magic Item Table 
page.lootgen.arcana=Arcana
page.lootgen.armaments=Armaments
page.lootgen.implements=Implements
page.lootgen.relics=Relics
page.lootgen.common=Common
page.lootgen.uncommon=Uncommon
page.lootgen.rare=Rare
page.lootgen.very_rare=Very Rare
page.lootgen.legendary=Legendary
page.lootgen.roll_loot=Roll Loot
page.lootgen.clear_output=Clear Output
page.lootgen.individual_treasure=Individual Treasure
page.lootgen.random_treasure_by_cr=Random Treasure by CR
page.lootgen.challenge_rating=Challenge Rating
page.lootgen.is_treasure_hoard=Is Treasure Hoard?
page.lootgen.loot_tables=Loot Tables
page.lootgen.party_loot=Party Loot
page.lootgen.dragon_hoard=Dragon Hoard
page.lootgen.wyrmling=Wyrmling
page.lootgen.young=Young
page.lootgen.adult=Adult
page.lootgen.ancient=Ancient
page.lootgen.gems_art_objects_generator=Gems/Art Objects Generator
parser.source.DrDe=Dragon Deleves
