common.no-data=No Data
common.feat=Feat
common.background=Background
common.species=Species
common.creature=Creature
common.source=Source
common.type=Type
common.author=Author
common.authors=Authors
common.origin=Origin
common.any=Any
common.name=Name
common.until=Until
common.or=or
common.hit_points=Hit Points
common.hit_dice=Hit Dice
common.armor_class=Armor Class
common.speed=Speed
common.proficiency_bonus=Proficiency Bonus
common.challenge_rating=Challenge Rating
common.challenge=Challenge
common.spell_level=Spell Level
common.skills=Skills
common.senses=Senses
common.languages=Languages
common.actions=Actions
common.saving_throws=Saving Throws
common.saving_throw=Saving Throw
common.campaign=Campaign
common.round=Round
common.minute=Minute
common.minutes=Minutes
common.hour=Hour
common.hours=Hours
common.day=Day
common.days=Days
common.week=Week
common.month=Month
common.year=Year
common.button.save=Save
common.button.search=Search
common.button.reset=Reset
common.button.clear=Clear
common.button.add=Add
common.button.confirm=Confirm
common.button.select=Select
common.button.delete=Delete
common.button.cancel=Cancel
common.button.remove=Remove
common.button.hide=Hide
common.button.show=Show
common.button.yes=Yes
common.button.no=No
common.button.update=Update
common.button.export=Export
common.button.get=Get
common.button.save_to_url=Save to URL
common.button.save_to_file=Save to File
common.button.load_from_file=Load from File
common.button.load_from_url=Load from URL
common.button.copy_as_text=Copy as Text
common.button.browse_source_repository=Browse Source Repository
common.button.export_list_as_url=Export List as URL
common.button.update_all=Update All
common.button.delete_all=Delete All
common.button.mass=Mass
common.button.manage_contents=Manage Contents
common.button.view_contents=View Contents
common.button.view_json=View JSON
common.button.reroll=reroll
common.button.move=Move
common.button.close=Close
common.button.configure=Configure
common.tabs.stat_block=Stat Block
common.tabs.info=Info
common.tabs.images=Images
common.tabs.data=Data
common.tabs.markdown=Markdown
common.tabs.no_info=No information available.
common.tabs.no_image=No images available
common.filter.filter_search_for=Filter/Search for
common.filter.manage_defaults=Manage Defaults
common.filter.take_snapshot=Take Snapshot
common.filter.take_snapshot_and_make_default=Take Snapshot and Make Default
common.filter.manage_snapshot=Manage Snapshot
common.filter.include_variants=Include Variants
common.filter.include_references=Include References
common.filter.include_references_tooltip=Consider entities as belonging to every source they appear in (i.e. reprints) as well as their primary source
common.preferences.preferences=Preferences
common.preferences.appearance=Appearance
common.preferences.theme=Theme
common.preferences.browser_default=Browser Default
common.preferences.day_mode=Day Mode
common.preferences.night_mode_classic=Night Mode (Classic)
common.preferences.night_mode_clean=Night Mode (Clean)
common.preferences.style=Style
common.preferences.wide_mode=Wide Mode (Experimental)
page.book.page_subtitle=Browse content. Press F to find, and G to go to page.
page.enconterbuilder.rules_note=Based on the encounter building rules in the
page.enconterbuilder.back_to_stat_blocks=Back to Stat Blocks
page.enconterbuilder.shift_for_multi_line_format=Shift for Multi-Line Format
page.enconterbuilder.shift_to_reset_players=Shift to Reset Players
page.classes.hit_points_at_first_level=Hit Points at 1st Level
page.classes.hit_points_at_higher_levels=Hit Points at Higher Levels
page.classes.proficiencies=Proficiencies
page.classes.armor=Armor
page.classes.weapons=Weapons
page.classes.tools=Tools
page.classes.skills=Skills
page.classes.class_feature_options_variants=Class Feature Options/Variants
page.classes.display_class_if_any_subclass_is_visible=Display Class if Any Subclass is Visible
page.backgrounds.alert=Alert
page.backgrounds.crafter=Crafter
page.backgrounds.healer=Healer
page.backgrounds.initiate_of_high_sorcery=Initiate of High Sorcery
page.backgrounds.lucky=Lucky
page.backgrounds.musician=Musician
page.backgrounds.rune_shaper=Rune Shaper
page.backgrounds.savage_attacker=Savage Attacker
page.backgrounds.scion_of_the_outer_planes=Scion of the Outer Planes
page.backgrounds.skilled=Skilled
page.backgrounds.squire_of_solamnia=Squire of Solamnia
page.backgrounds.Strike of the Giants=Strike of the Giants
page.backgrounds.Strixhaven Initiate=Strixhaven Initiate
page.backgrounds.Tavern Brawler=Tavern Brawler
page.backgrounds.tough=Tough
page.backgrounds.magic_initiate=Magic Initiate
page.backgrounds.magic_initiate__cleric=Magic Initiate; Cleric
page.backgrounds.magic_initiate__druid=Magic Initiate; Druid
page.backgrounds.magic_initiate__wizard=Magic Initiate; Wizard
page.backgrounds.origin=Origin
page.feats.repeatable=Repeatable
page.feats.not_repeatable=Not Repeatable
page.charcreationoptions.supernatural_gift=Supernatural Gift
page.charcreationoptions.optional_feature=Optional Feature
page.charcreationoptions.dark_gift=Dark Gift
page.charcreationoptions.replacement_feature__background=Replacement Feature: Background
page.charcreationoptions.character_secret=Character Secret
page.optionalfeatures.artificer_infusion=Artificer Infusion
page.optionalfeatures.elemental_discipline=Elemental Discipline
page.optionalfeatures.eldritch_invocation=Eldritch Invocation
page.optionalfeatures.metamagic=Metamagic
page.optionalfeatures.maneuver=Maneuver
page.optionalfeatures.maneuver__battle_master=Maneuver, Battle Master
page.optionalfeatures.maneuver__cavalier=Maneuver, Cavalier
page.optionalfeatures.arcane_shot=Arcane Shot
page.optionalfeatures.other=Other
page.optionalfeatures.fighting_style__fighter=Fighting Style; Fighter
page.optionalfeatures.fighting_style__bard=Fighting Style; Bard
page.optionalfeatures.fighting_style__paladin=Fighting Style; Paladin
page.optionalfeatures.fighting_style__ranger=Fighting Style; Ranger
page.optionalfeatures.pact_boon=Pact Boon
page.optionalfeatures.rune_knight_rune=Rune Knight Rune
page.optionalfeatures.alchemical_formula=Alchemical Formula
page.optionalfeatures.travelers_trick=Traveler's Trick
page.statgen.additional_feats=Additional Feats
page.statgen.number_of_additional_feats=Number of additional feats
page.statgen.allow_origin_customization=Allow Origin Customization
page.lootgen.magic_item_table_=Magic Item Table 
page.lootgen.arcana=Arcana
page.lootgen.armaments=Armaments
page.lootgen.implements=Implements
page.lootgen.relics=Relics
page.lootgen.common=Common
page.lootgen.uncommon=Uncommon
page.lootgen.rare=Rare
page.lootgen.very_rare=Very Rare
page.lootgen.legendary=Legendary
page.lootgen.roll_loot=Roll Loot
page.lootgen.clear_output=Clear Output
page.lootgen.individual_treasure=Individual Treasure
page.lootgen.adventure_rewards_by_cr=Adventure Rewards by CR
page.lootgen.random_treasure_by_cr=Random Treasure by CR
page.lootgen.is_treasure_hoard=Is Treasure Hoard?
page.lootgen.treasure_hoard=Treasure Hoard
page.lootgen.character_level=Character Level
page.lootgen.hoard=Hoard
page.lootgen.magic_items=Magic Items
page.lootgen.loot_tables=Loot Tables
page.lootgen.party_loot=Party Loot
page.lootgen.dragon_hoard=Dragon Hoard
page.lootgen.dragon_age=Dragon Age
page.lootgen.wyrmling=Wyrmling
page.lootgen.young=Young
page.lootgen.adult=Adult
page.lootgen.ancient=Ancient
page.lootgen.prefer_random_magic_items=Prefer Random Magic Items
page.lootgen.gems_art_objects=Gems/Art Objects
page.lootgen.gems_art_objects_generator=Gems/Art Objects Generator
page.lootgen.include_gems=Include Gems
page.lootgen.include_art_objects=Include Art Objects
page.lootgen.target_gold_amount=Target Gold Amount
page.lootgen.roughly=Roughly
page.lootgen.gemstones=gemstones
page.lootgen.art_objects=art objects
page.manageprelease.manage_prerelease_content=Manage Prerelease Content
page.manageprelease.manage_prerelease_content_subtitle=View, Add, and Delete Prerelease Content.
page.manageprelease.prerelease_content=prerelease content
page.manageprelease.prerelease=prerelease
page.manageprelease.load_all_partnered_content=Load All Partnered Content
page.manageprelease.load_partnered_content=Load Partnered Content
page.manageprelease.are_you_sure_you_want_to_load_all_partnered_content=Are you sure you want to load all partnered content?
page.manageprelease.export_prerelease_content_homebrew_list_as_url=`Export Prerelease Content/Homebrew List as URL`
page.manageprelease.view_source=View Source
page.makebrew.title=Homebrew Builder
page.makebrew.subtitle=Input values on left, view the results on the right.
page.spells.special=Special
page.spells.instantaneous=Instantaneous
page.spells.permanent=Permanent
page.spells.concentration=Concentration
page.spells.instant=Instant
page.dmscreen.embed=Embed
page.dmscreen.paste_image_url=Paste image URL
page.dmscreen.paste_youtube_url=Paste YouTube URL
page.dmscreen.paste_twitch_url=Paste Twitch URL
page.dmscreen.paste_any_url=Paste any URL
page.dmscreen.initiative_tracker=Initiative Tracker
page.dmscreen.creature_status=Creature/Status
page.dmscreen.initiative_score=Initiative Score
page.dmscreen.add_contition=Add Condition
page.dmscreen.shown_in_player_view=Shown in player view
page.dmscreen.hidden_in_player_view=Hidden in player view
page.dmscreen.shift_to_delete_similar=SHIFT to Also Delete Similar
page.dmscreen.add_player=Add Player
page.dmscreen.add_creature=Add Creature
page.dmscreen.previous_turn=Previous Turn
page.dmscreen.next_turn=Next Turn
page.dmscreen.round=Round
page.dmscreen.sort_alphabetically=Sort Alphabetically
page.dmscreen.sort_numerically=Sort Numerically
page.dmscreen.player_view=Player View
page.dmscreen.shift_to_open_standard_view=SHIFT to Open &quot;Standard&quot; View
page.dmscreen.lock_tracker=Lock Tracker
page.dmscreen.unlock_tracker=Unlock Tracker
page.dmscreen.shift_to_open_settings=SHIFT to Open &quot;Settings&quot;
page.dmscreen.import_encounter_from_the_bestiary=Import an encounter from the Bestiary
page.dmscreen.reset_tracker=Reset Tracker
parser.core=Core
parser.optional=Optional
parser.prerelease=Prerelease
parser.variant=Variant
parser.variant_optional=Variant Optional
parser.variant_variant=Variant Variant
parser.unknown=Unknown
parser.source.drde=Dragon Deleves
parser.source.screen=Dungeon Master's Screen
parser.source.screenwildernesskit=Dungeon Master's Screen: Wilderness Kit
parser.source.screendungeonkit=Dungeon Master's Screen: Dungeon Kit
parser.source.screenspelljammer=Dungeon Master's Screen: Spelljammer
parser.source.xscreen=Dungeon Master's Screen (2024)
parser.source.dmtcrg=The Deck of Many Things: Card Reference Guide
parser.source.hotb=Heroes of the Borderlands
