common.no-data=No Data
common.button.save=Save
common.button.search=Search
common.button.reset=Reset
common.button.clear=Clear
common.button.add=Add
common.button.confirm=Confirm
common.button.select=Select
common.button.delete=Delete
common.button.cancel=Cancel
common.button.remove=Remove
common.button.yes=Yes
common.button.no=No
common.button.save_to_url=Save to URL
common.button.save_to_file=Save to File
common.button.load_from_file=Load from File
common.button.copy_as_text=Copy as Text
common.tabs.stat_block=Stat Block
common.tabs.info=Info
common.tabs.images=Images
common.tabs.data=Data
common.tabs.markdown=Markdown
common.tabs.no_info=No information available.
common.tabs.no_image=No images available
page.book.page_subtitle=Browse content. Press F to find, and G to go to page.
page.enconterbuilder.rules_note=Based on the encounter building rules in the
page.enconterbuilder.back_to_stat_blocks=Back to Stat Blocks
page.enconterbuilder.shift_for_multi_line_format=Shift for Multi-Line Format
page.enconterbuilder.shift_to_reset_players=Shift to Reset Players
parser.source.DrDe=Dragon Deleves
