common.no-data=沒有數據
common.feat=专长
common.background=背景
common.species=种族
common.button.save=保存
common.button.search=檢索
common.button.reset=重置
common.button.clear=清空
common.button.add=新增
common.button.confirm=確認
common.button.select=選擇
common.button.delete=刪除
common.button.cancel=取消
common.button.remove=移除
common.button.hide=隱藏
common.button.show=顯示
common.button.yes=是
common.button.no=否
common.button.save_to_url=保存到URL
common.button.save_to_file=保存到文件
common.button.load_from_file=從文件加載
common.button.copy_as_text=複製為文本
common.tabs.stat_block=资料卡
common.tabs.info=信息
common.tabs.images=圖片
common.tabs.data=數據
common.tabs.markdown=Markdown
common.tabs.no_info=没有可用的信息。
common.tabs.no_image=没有可用的图片。
common.filter.filter_search_for=筛选/搜索
page.book.page_subtitle=浏览内容。按F搜索，按G跳转页面。
page.enconterbuilder.rules_note=基于遭遇构筑规则构建，源于
page.enconterbuilder.back_to_stat_blocks=返回統計卡
page.enconterbuilder.shift_for_multi_line_format=按住SHIFT多行格式
page.enconterbuilder.shift_to_reset_players=按住SHIFT重置玩家
page.backgrounds.alert=警覺
page.backgrounds.crafter=工匠
page.backgrounds.healer=醫者
page.backgrounds.initiate_of_high_sorcery=高等术法學徒
page.backgrounds.lucky=1
page.backgrounds.musician=1
page.backgrounds.rune_shaper=符文雕刻師
page.backgrounds.savage_attacker=凶蛮打手
page.backgrounds.scion_of_the_outer_planes=外层位面子嗣
page.backgrounds.skilled=熟練
page.backgrounds.squire_of_solamnia=索拉尼亞侍从
page.backgrounds.Strike of the Giants=巨人打击
page.backgrounds.Strixhaven Initiate=
page.backgrounds.Tavern Brawler=
page.backgrounds.tough=
page.backgrounds.magic_initiate=魔法學徒
page.backgrounds.magic_initiate__cleric=魔法學徒（牧師）
page.backgrounds.magic_initiate__druid=魔法學徒（德魯伊）
page.backgrounds.magic_initiate__wizard=魔法學徒（法師）
page.feats.repeatable=可重複
page.feats.not_repeatable=不可重複
page.charcreationoptions.supernatural_gift=超自然赠礼
page.charcreationoptions.optional_feature=可选特性
page.charcreationoptions.dark_gift=黑暗赠礼
page.charcreationoptions.replacement_feature__background=可替换特性：背景
page.charcreationoptions.character_secret=角色秘密
page.optionalfeatures.artificer_infusion=奇械師注法
page.optionalfeatures.elemental_discipline=
page.optionalfeatures.eldritch_invocation=
page.optionalfeatures.metamagic=
page.optionalfeatures.maneuver=
page.optionalfeatures.maneuver__battle_master=
page.optionalfeatures.maneuver__cavalier=
page.optionalfeatures.arcane_shot=奥术射击
page.optionalfeatures.other=
page.optionalfeatures.fighting_style__fighter=
page.optionalfeatures.fighting_style__bard=
page.optionalfeatures.fighting_style__paladin=
page.optionalfeatures.fighting_style__ranger=
page.optionalfeatures.pact_boon=
page.optionalfeatures.rune_knight_rune=
page.optionalfeatures.alchemical_formula=
page.optionalfeatures.travelers_trick=
page.statgen.additional_feats=额外专长
page.statgen.number_of_additional_feats=额外专长数量
parser.source.DrDe=巨龙迷城
